strengthPlus:
  # 是否允许调试模式
  debug: true
  # 标题
  title: StrengthPlus
  # 通知
  notify:
    #成功时通知
    success: '强化成功'
    #失败时通知
    fail: '强化失败'
  broadcast:
    success: '恭喜%player%将他的装备强化到%level%级'
    safe: '很遗憾，%player%在将他的装备强化到%level%级的时候强化炉发生了爆炸，好在装备保护强化券保护了装备没有被摧毁！'
    fail: '很遗憾，%player%在将他的装备强化到%level%级的时候强化炉发生了爆炸，装备被摧毁了！'
damage:
  # 单手剑伤害强化倍率
  swoad: 1.5
  # 弓箭伤害强化倍率
  bow: 1.5
  # 弩箭伤害强化倍率
  crossbow: 1.2
defence:
  # 一级护甲带来的伤害减免
  armorDefence: 0.5
  # 最小造成伤害
  minDamage: 1


