name: strengthPlus
main: top.mccat.StrengthPlus
version: 2.1-Alpha
api-version: 1.18.2
commands:
  sp:
    description: "strengthPlus command"
    usage: /sp
    aliases: [ stregnthplus,qh ]
    permission-message: "§a[StrengthPlus]§c你无权使用该指令"